name: CI/CD Petshop Celeiro ğŸ¶

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: ${{ secrets.DOCKER_USERNAME }}/petshop-backend
  IMAGE_FRONTEND: ${{ secrets.DOCKER_USERNAME }}/petshop-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ” Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ³ Build Backend
        run: docker build -t $IMAGE_BACKEND ./backend

      - name: ğŸ“¤ Push Backend
        run: docker push $IMAGE_BACKEND

      - name: ğŸ³ Build Frontend
        run: docker build -t $IMAGE_FRONTEND ./frontend

      - name: ğŸ“¤ Push Frontend
        run: docker push $IMAGE_FRONTEND

